"""Render the standalone Zhi Systems promotional film (16:9, 1920x1080, 50 seconds)."""
from pathlib import Path
import subprocess
import textwrap

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "dist" / "videos"
OUT.mkdir(parents=True, exist_ok=True)
WORK = OUT / "zhi_promo_work"
WORK.mkdir(exist_ok=True)

W, H, FPS, DURATION = 1920, 1080, 30, 50
LOGO = ROOT / "client" / "public" / "zhi-systems-logo.png"
BADGE_AI = ROOT / "attached_assets" / "ZHI_AI_FUNDAMENTALS_BADGE_1781725917586.png"
BADGE_MATH = ROOT / "attached_assets" / "ZHI_AI_MATH_FUNDAMENTALS_BADGE_1781730555335.png"
HERO = ROOT / "attached_assets" / "generated_images" / "zhi_video_hero.png"
AUDIO = WORK / "voiceover.mp3"

SCRIPT = """Zhi Systems creates customized AI-powered apps for education, finance, writing, psychology, and cognitive enhancement.

For inquiry without the canned answer, meet FreudGPT: a conversational AI grounded in the voices and actual writings of psychoanalysis, philosophy, and critical theory.

For serious intellectual work, Genius 101 lets you converse, question, and generate long-form work in the voice of history's greatest minds.

And through ZHI Microcertifications, learners earn verified, AI-taught, AI-graded credentials, including AI Fundamentals and AI Math Fundamentals.

Build a sharper system for how people learn, think, write, and decide. Go to ZhiSystems.ai."""

def run(cmd):
    print("+", " ".join(map(str, cmd)))
    subprocess.run(cmd, check=True)

def esc(s):
    return s.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'").replace("%", "\\%")

def text_file(name, text):
    p = WORK / name
    p.write_text(text, encoding="utf-8")
    return p

def main():
    # Voice is generated by edge-tts before this renderer runs.
    # Scenes are animated at 30fps using moving image crops and filmic overlays.
    title = text_file("title.txt", "CUSTOM AI FOR HUMAN THOUGHT")
    all_fields = text_file("fields.txt", "EDUCATION  /  FINANCE  /  WRITING  /  PSYCHOLOGY  /  COGNITIVE ENHANCEMENT")
    freud = text_file("freud.txt", "FREUDGPT  —  THE THINKERS SPEAK AGAIN")
    genius = text_file("genius.txt", "GENIUS 101  —  CONVERSE. QUESTION. GENERATE.")
    cert = text_file("cert.txt", "ZHI MICROCERTIFICATIONS  —  AI FUNDAMENTALS  /  AI MATH FUNDAMENTALS")
    cta = text_file("cta.txt", "BUILD WHAT THINKING NEEDS.  /  GO TO ZHISYSTEMS.AI")

    font_display = "/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf"
    font_body = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    # A living, editorial video bed with vignette, grain and deliberate camera movement.
    base = "[0:v]format=rgba,drawbox=x=0:y=0:w=1920:h=1080:color=0x101824:t=fill[v0]"
    filters = [base]
    # Hero image inhabits opening and title.
    if HERO.exists():
        filters.append(f"movie={HERO},scale=2400:-1,crop={W}:{H}:x='220+80*sin(0.17*t)':y='120+40*cos(0.13*t)',format=rgba,colorchannelmixer=aa=0.42[hero]")
        filters.append("[v0][hero]overlay=0:0:enable='between(t,0,12)'[v1]")
    else:
        filters.append("[v0]null[v1]")
    # composited visual assets are present on their content beats
    filters.extend([
        f"movie={LOGO},scale=240:-1,format=rgba,colorchannelmixer=aa=0.92[logo]",
        "[v1][logo]overlay=92:72:enable='between(t,0,50)'[v2]",
        f"movie={BADGE_AI},scale=265:-1,format=rgba[ai]",
        f"movie={BADGE_MATH},scale=265:-1,format=rgba[math]",
        "[v2][ai]overlay=1270:470:enable='between(t,34,43)'[v3]",
        "[v3][math]overlay=1540:470:enable='between(t,34,43)'[v4]",
        # kinetic editorial type, with subtle in/out alpha choreography
        f"[v4]drawtext=fontfile={font_display}:textfile={title}:fontcolor=0xF1E7D0:fontsize=78:x=115:y=390:alpha='if(lt(t,0.6),0,if(lt(t,1.4),(t-0.6)/0.8,if(lt(t,8),1,if(lt(t,9),(9-t),0))))'[v5]",
        f"[v5]drawtext=fontfile={font_body}:text='ZHI SYSTEMS  /  INTELLIGENCE, APPLIED':fontcolor=0xD1A758:fontsize=28:x=120:y=210:alpha='between(t,0.8,8.8)'[v6]",
        f"[v6]drawtext=fontfile={font_display}:textfile={all_fields}:fontcolor=0xF1E7D0:fontsize=40:x=135:y=445:alpha='if(lt(t,9),0,if(lt(t,10),(t-9),if(lt(t,15),1,if(lt(t,16),(16-t),0))))'[v7]",
        f"[v7]drawtext=fontfile={font_body}:text='CUSTOM SYSTEMS, BUILT AROUND THE WAY PEOPLE ACTUALLY THINK':fontcolor=0xD1A758:fontsize=28:x=140:y=290:alpha='between(t,9.5,15.5)'[v8]",
        f"[v8]drawtext=fontfile={font_display}:textfile={freud}:fontcolor=0xF1E7D0:fontsize=52:x=140:y=430:alpha='if(lt(t,16),0,if(lt(t,17),(t-16),if(lt(t,25),1,if(lt(t,26),(26-t),0))))'[v9]",
        f"[v9]drawtext=fontfile={font_body}:text='PSYCHOANALYSIS  /  PHILOSOPHY  /  CRITICAL THEORY':fontcolor=0xB65745:fontsize=28:x=145:y=250:alpha='between(t,16.5,25.5)'[v10]",
        f"[v10]drawtext=fontfile={font_display}:textfile={genius}:fontcolor=0xF1E7D0:fontsize=50:x=700:y=430:alpha='if(lt(t,25),0,if(lt(t,26),(t-25),if(lt(t,34),1,if(lt(t,35),(35-t),0))))'[v11]",
        f"[v11]drawtext=fontfile={font_body}:text='GENIUS 101  /  INTELLECTUAL CONVERSATION':fontcolor=0xD1A758:fontsize=25:x=960:y=250:alpha='between(t,25.5,34.5)'[v12]",
        f"[v12]drawtext=fontfile={font_display}:textfile={cert}:fontcolor=0xF1E7D0:fontsize=39:x=130:y=285:alpha='if(lt(t,34),0,if(lt(t,35),(t-34),if(lt(t,43),1,if(lt(t,44),(44-t),0))))'[v13]",
        f"[v13]drawtext=fontfile={font_display}:textfile={cta}:fontcolor=0xF1E7D0:fontsize=54:x=130:y=420:alpha='if(lt(t,43),0,if(lt(t,44),(t-43),if(lt(t,49),1,49.8-t)))'[v14]",
        f"[v14]drawtext=fontfile={font_body}:text='ZHI SYSTEMS':fontcolor=0xD1A758:fontsize=29:x=133:y=200:alpha='between(t,43.3,49.7)'[v15]",
        # moving brass orbit and a refined grain pass
        "[v15]drawbox=x='-250+mod(t*330,2400)':y=100:w=5:h=880:color=0xD1A758@0.3:t=fill,"
        "noise=alls=8:allf=t+u:all_seed=158,format=yuv420p[outv]"
    ])
    complex_filter = ";".join(filters)
    run(["ffmpeg", "-y", "-f", "lavfi", "-i", f"color=s={W}x{H}:r={FPS}:d={DURATION}", "-i", str(AUDIO), "-filter_complex", complex_filter,
         "-map", "[outv]", "-map", "1:a", "-c:v", "libx264", "-preset", "medium", "-crf", "18",
         "-c:a", "aac", "-b:a", "192k", "-shortest", "-movflags", "+faststart", str(OUT / "zhi-systems-promo-16x9.mp4")])

if __name__ == "__main__":
    main()